### ISSUE TITLE
Unexpected identifier error when generating new routes

### ISSUE THREAD

**Issue by beerlington** [ember-cli/ember-router-generator#22]
I'm getting an error trying to generate routes and have no idea what is causing it. I'm on the latest version of ember-cli and ember. I did a fresh install of ember-cli and everything else just to be sure it wasn't an outdated package.

It's generating the route and template correctly, but blows up before adding the test. Generating controllers, templates, etc works fine.

```
ember g route my-route 
```

```
version: 2.3.0
installing route
  create app/routes/my-route.js
  create app/templates/my-route.hbs
Line 6: Unexpected identifier
Error: Line 6: Unexpected identifier
    at throwError (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:2692:21)
    at throwUnexpected (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:2736:13)
    at expect (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:2763:13)
    at parseObjectProperty (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:3102:17)
    at parseObjectInitialiser (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:3270:28)
    at parseVariableDeclaration (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:4650:18)
    at parseVariableDeclarationList (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:4690:23)
    at parseConstLetDeclaration (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:4721:24)
    at parseSourceElement (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:6267:24)
    at parseProgramElement (/Users/peterbrown/code/Test-UI/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:6323:16)
```

**Comment by dawistah** [comment]
I do also have problems generating routes.

<pre><code>user@laptop ~/code $ ember g route about</code></pre>

<pre><code>version: 2.4.2
installing route
  create app/routes/about.js
  create app/templates/about.hbs
Line 10: Unexpected token {
Error: Line 10: Unexpected token {
    at throwError (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:2692:21)
    at throwUnexpected (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:2754:9)
    at expect (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:2763:13)
    at parseArguments (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:3470:17)
    at parseLeftHandSideExpressionAllowCall (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:3534:24)
    at parsePostfixExpression (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:3570:20)
    at parseUnaryExpression (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:3637:16)
    at parseBinaryExpression (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:3727:16)
    at parseConditionalExpression (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:3787:16)
    at parseAssignmentExpression (/code/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast/node_modules/esprima-fb/esprima.js:4038:16) </code></pre>

**Comment by blimmer** [comment]
I'm also experiencing this problem when using destructuring. Place this line in your `router.js` file:

```
const { get, inject: { service } } = Ember;
```

and then all `ember g route <route-name>` will fail on that line. Looks like esprima parser freaks out with that structure.

**Comment by stefanpenner** [comment]
I suspect the version of esprima needs to be bumped.

**Comment by blimmer** [comment]
Wrote a failing test and fixed with dependency upgrades. See #24 .
