### ISSUE TITLE
syntax errors when parsing end up being quite cryptic 

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-router-generator#23]

**Comment by rwjblue** [comment]
```
 ~/ % ember generate route communities-landing
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing route
  create app/routes/communities-landing.js
  create app/templates/communities-landing.hbs
Line 8: Unexpected token =
Error: Line 8: Unexpected token =
    at throwError (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:2692:21)
    at throwUnexpected (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:2754:9)
    at expect (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:2763:13)
    at parseObjectProperty (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:3102:17)
    at parseObjectInitialiser (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:3270:28)
    at parseVariableDeclaration (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:4650:18)
    at parseVariableDeclarationList (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:4690:23)
    at parseConstLetDeclaration (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:4721:24)
    at parseSourceElement (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:6267:24)
    at parseProgramElement (/Users/jhhillis/Development/web-client/node_modules/ember-router-generator/node_modules/esprima-fb/esprima.js:6323:16)
```

**Comment by rwjblue** [comment]
^^ was caused by `const { Router } = Ember;`

**Comment by abuiles** [comment]
This was fixed with https://github.com/ember-cli/ember-router-generator/pull/24
