### ISSUE TITLE
ember g route failing to generate test files

### ISSUE THREAD

**Issue by sndy** [ember-cli/ember-router-generator#39]
ember g route failing with :

ember g route psr/conduct
installing route
  create app/routes/psr/conduct.js
  create app/templates/psr/conduct.hbs
Cannot read property 'body' of undefined
**TypeError: Cannot read property 'body' of undefined**
    at EmberRouterGenerator.add (/home/sndy/sndy/work/wb-ui-deal-activities/node_modules/ember-cli/node_modules/ember-router-generator/lib/ember-router-generator.js:51:50)**
    at writeRoute (/home/sndy/sndy/work/wb-ui-deal-activities/node_modules/ember-cli/blueprints/route/index.js:119:33)
    at Class.updateRouter (/home/sndy/sndy/work/wb-ui-deal-activities/node_modules/ember-cli/blueprints/route/index.js:95:5)
    at Class.module.exports.afterInstall (/home/sndy/sndy/work/wb-ui-deal-activities/node_modules/ember-cli/blueprints/route/index.js:78:18)
    at tryCatch (/home/sndy/sndy/work/wb-ui-deal-activities/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/home/sndy/sndy/work/wb-ui-deal-activities/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/home/sndy/sndy/work/wb-ui-deal-activities/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/home/sndy/sndy/work/wb-ui-deal-activities/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2414:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

Able to generate the routes, however creation of route-tests are failing at- **route.mapNode.arguments[0].body.body;**

ember-cli: 2.5.0
ember-router-generator : 1.2.3
recast:  0.11.23

**Comment by ming-codes** [comment]
I got the same issue, but I found out why it's happening.

We moved the route map out of the router file and moved it to `./routes.js`. The ast lookup can't handle this case.

**Comment by trentmwillis** [comment]
@sndy is your error occurring within an Engine as well?

@ming-codes there are likely updates that need to occur in this package as well as in the blueprint itself. In the blueprint we'll need to update the logic that determines which file to modify ([here](https://github.com/emberjs/ember.js/blob/b1c259b21cd6e3ccb7cdb84484bffefe41286d7b/blueprints/route/index.js#L127-L137)).

**Comment by sndy** [comment]
@trentmwillis we are still on addons, let me check if moving to engines will overcome this error.

Thanks @ming-codes & @trentmwillis
